library(CSOA)
library(dplyr)
library(GSABenchmark)
library(hammers)
library(qs)
library(scRNAseq)
library(scuttle)
library(Seurat)
library(LISTO)
library(ggplot2)
library(patchwork)

source('tools.R')
source('run_methods.R')
source('run_benchmark.R')
source('run_shuffle.R')

runMethods()
runBenchmark()
runShuffle()
